default:
    image: python:3.8

variables:
    PIP_DIR: "/root/.pip"
    PIP_FILE: "/root/.pip/pip.conf"

stages:
    - build
    - deploy

before_script:
    - echo "Initialize environment"
    - apt-get update -qy
    - apt-get install -y python-dev python3-pip
    - apt-get install -y python3-sphinx
    - 'mkdir $PIP_DIR'
    - 'touch $PIP_FILE'
    - 'echo [global] >> $PIP_FILE'
    - 'echo index-url = http://$DEVPI_HOST:3141/$DEVPI_INDEX/+simple/ >> $PIP_FILE'
    - 'echo [search] >> $PIP_FILE'
    - 'echo index = http://$DEVPI_HOST:3141/$DEVPI_INDEX/ >> $PIP_FILE'
    - 'echo [install] >> $PIP_FILE'
    - 'echo trusted-host = $DEVPI_HOST >> $PIP_FILE'
    - pip install -r requirements.txt

builds:
    stage: build
    script:
    - echo "Generate package and sphinx documentation"
    - python setup.py bdist_wheel build_sphinx

production:
    stage: deploy
    script:
    - echo "publish revision"
    - export PYTHONPATH="$PWD"
    - bash -c "devpi use http://$DEVPI_HOST:3141/$DEVPI_INDEX"
    - bash -c "devpi login $DEVPI_LOGIN --password=$DEVPI_PASSWORD"
    - bash -c "devpi upload --format bdist_wheel"

    only:
    - tags
